services:
  swagger-merger:
    build:
      context: .
      dockerfile: ./swagger-merger/Dockerfile
    container_name: "openapi-swagger-merger"
    tty: true
    volumes:
      - type: bind
        source: "./workspace"
        target: "/workspace"
    command: >
      watch 'swagger-merger -i /workspace/documents/main.yaml -o /workspace/dist/openapi.yaml' /workspace/documents/

  redoc:
    image: redocly/redoc
    container_name: "openapi-redoc"
    ports:
      - "8010:80"
    volumes:
      - type: bind
        source: "./workspace/dist"
        target: "/usr/share/nginx/html/api"
    environment:
      SPEC_URL: api/openapi.yaml

  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "openapi-swagger-ui"
    ports:
      - "8011:8080"
    volumes:
      - type: bind
        source: ./workspace/dist
        target: /workspace/dist
    environment:
      SWAGGER_JSON: /workspace/dist/openapi.yaml

  api-mock:
    platform: linux/x86_64
    image: stoplight/prism:4
    container_name: "openapi-mock"
    ports:
      - "8012:4010"
    restart: always
    volumes:
      - type: bind
        source: ./workspace/dist
        target: /workspace/dist
    command: mock -h 0.0.0.0 /workspace/dist/openapi.yaml
