openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger Petstore
  license:
    name: MIT
servers:
  - url: http://localhost:8012
    description: mock server
  - url: http://localhost:3000
    description: development server for testing
  - url: http://staging-api.example.com
    description: staging server for testing
paths:
  /pets:
    $ref: ./paths/pets.yaml
  /pets/{petId}:
    $ref: ./paths/pets_petId.yaml